import { StyleSheet } from 'react-native';

export default StyleSheet.create({
  container: {
    paddingTop: 10,
    alignItems: 'center',
    backgroundColor: '#F8F9FA',
  },
  title: {
    fontSize: 22,
    fontWeight: 'bold',
    marginBottom: 20,
    color: '#2E7D32',
  },
  grid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    justifyContent: 'center',
  },
  monthCard: {
    backgroundColor: '#E8F5E9',
    paddingVertical: 20,
    paddingHorizontal: 15,
    borderRadius: 16,
    margin: 8,
    minWidth: '28%',
    alignItems: 'center',
    elevation: 3,
  },
  monthText: {
    fontSize: 16,
    fontWeight: '600',
    color: '#1B5E20',
  },
  suggestionButton: {
    backgroundColor: '#4CAF50',
    padding: 15,
    borderRadius: 20,
    marginTop: 25,
    width: '90%',
    alignItems: 'center',
  },
  suggestionText: {
    color: 'white',
    fontSize: 16,
    fontWeight: 'bold',
  },
  suggestionCard: {
    backgroundColor: 'white',
    padding: 20,
    marginRight: 15,
    marginLeft: 15,
    borderRadius: 20,
    marginTop: 10,
    shadowColor: '#000',
    shadowOpacity: 0.1,
    shadowRadius: 5,
    elevation: 3,
  },
  suggestionTitle: {
    fontSize: 18,
    fontWeight: 'bold',
    marginBottom: 10,
    color: '#388E3C',
  },
  suggestionText2: {
    fontSize: 15,
    color: '#333',
  },
  logincontainer: {
    flex: 1,
    justifyContent: 'center',
    padding: 20,
    backgroundColor: '#fff',
  },
  logocontainer: {
    backgroundColor: '#fff',
    alignItems: 'center',
    justifyContent: 'center',
    padding: 20,
  },
  logo: {
    width: 100,
    height: 100,
    resizeMode: 'contain',
  },
  logintitle: {
    fontSize: 24,
    marginBottom: 20,
    fontWeight: 'bold',
    textAlign: 'center',
  },
  logininput: {
    borderWidth: 1,
    borderColor: '#ddd',
    padding: 10,
    marginBottom: 15,
    borderRadius: 8,
  },
  loginbutton: {
    backgroundColor: '#333',
    padding: 15,
    borderRadius: 8,
    alignItems: 'center',
  },
  loginbuttonText: {
    color: '#fff',
    fontSize: 16,
  },
  profilecard: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#F8F8F8',
    padding: 14,
    borderRadius: 12,
    shadowColor: '#000',
    shadowOpacity: 0.05,
    shadowOffset: { width: 0, height: 2 },
    shadowRadius: 4,
    elevation: 2,
    marginTop: 10,
    marginBottom: 10,
  },
  profileavatarContainer: {
    justifyContent: 'center',
    alignItems: 'center',
    marginRight: 14,
  },
  profileavatar: {
    width: 60,
    height: 60,
    borderRadius: 30,
    backgroundColor: '#ddd',
  },
  profileinfoContainer: {
    flex: 1,
    justifyContent: 'center',
  },
  profilename: {
    fontSize: 18,
    fontWeight: '600',
    color: '#333',
    marginBottom: 2,
  },
  profileusername: {
    fontSize: 15,
    color: '#777',
    marginBottom: 2,
  },
  profileemail: {
    fontSize: 14,
    color: '#555',
  },
  profilelogoutButton: {
    backgroundColor: '#ff4d4d',
    paddingVertical: 8,
    paddingHorizontal: 12,
    borderRadius: 8,
  },
  profilelogoutText: {
    color: '#fff',
    fontWeight: '600',
    fontSize: 14,
  },
});
